apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: nginx-argo-created
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc  
  source:
    chart: mychart 
    path: mychart
    repoURL: https://github.com/Proxypepe/argocd-exploring.git
    targetRevision: HEAD
    helm:
      releaseName: ngint_by_helm
